### ISSUE TITLE
Error after saving a group 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-users#2115]
**Case 1** 
1. Select system provider in grid then open wizard for new group 
2. Fill in a name then click on Save button 

![image](https://github.com/user-attachments/assets/a3bcfdbd-0456-420f-968e-96b732615481)

```
bundle.js:2 
TypeError: Cannot read properties of undefined (reading 'wasAlreadyShownAndLoaded')
    at UserBrowsePanel.appendPrincipal (bundle.js:2:1147113)
    at UserBrowsePanel.appendUserItemNode (bundle.js:2:1146679)
    at bundle.js:2:1145902
    at bundle.js:2:1198694
    at Array.forEach (<anonymous>)
    at PrincipalServerEventsHandler.notifyUserItemCreated (bundle.js:2:1198673)
    at PrincipalServerEventsHandler.handleUserItemCreated (bundle.js:2:1198363)
    at PrincipalServerEventsHandler.handleUserItem (bundle.js:2:1198013)
    at bundle.js:2:1196826
    at _fulfilled (bundle.js:2:1109826)
﻿

```
**Case 2** 
The same issue with saving an user with riles 

![image](https://github.com/user-attachments/assets/28f13e68-16aa-4a5b-9c09-9fd1d4ffa4fa)

**Comment by sgauruseu** [comment]
All tests passed
