### ISSUE TITLE
NPE after deleting a group or user

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-users#325]
Delete a group in Users

![image](https://user-images.githubusercontent.com/3728712/80346504-8740aa00-8873-11ea-80c2-1b1c96d2272f.png)

`Caused by: java.lang.NullPointerException: null
	at com.enonic.xp.core.impl.security.SecurityServiceImpl.lambda$queryDirectMemberships$12(SecurityServiceImpl.java:328)
	at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:102)
	at com.enonic.xp.core.impl.security.SecurityServiceImpl.callWithContext(SecurityServiceImpl.java:1179)
	at com.enonic.xp.core.impl.security.SecurityServiceImpl.queryDirectMemberships(SecurityServiceImpl.java:324)
	at com.enonic.xp.core.impl.security.SecurityServiceImpl.getMemberships(SecurityServiceImpl.java:362)
	at com.enonic.xp.lib.auth.GetMembershipsHandler.getMemberships(GetMembershipsHandler.java:45)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$408$5125AA$auth.L:1#getMemberships(com.enonic.xp.app.users:/lib/xp/auth.js:175)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$407$713AA$principals.L:1#getMemberships(com.enonic.xp.app.users:/lib/principals.js:19)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$409$2459A$principal.L:1#resolve-5(com.enonic.xp.app.users:/services/graphql/types/objects/principal.js:84)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:657)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:120)
	at com.enonic.xp.script.impl.value.FunctionScriptValue.call(FunctionScriptValue.java:36)`

**Comment by sgauruseu** [comment]
Verified in branch 3.0
