### ISSUE TITLE
UserStore wizard -  error in console when  saving new store

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-users#76]
1. Open UserStore wizard , type a name
2. click on Save
BUG: notification message does not appear and error appears in browser console:
  `_all.js:1 Error: UserStore[test1] not found
    at CreateUserStoreRequest.SaveUserStoreRequest.userStorefromJson (http://localhost:8080/admin/tool/com.enonic.xp.app.users/main/_/asset/com.enonic.xp.app.users:1524820438/js/bundle.js:1:40100)
    at http://localhost:8080/admin/tool/com.enonic.xp.app.users/main/_/asset/com.enonic.xp.app.users:1524820438/js/bundle.js:1:39933
From previous event:
    at UserStoreWizardPanel.WizardPanel.saveChanges (http://localhost:8080/admin/tool/com.enonic.xp.app.users/main/_/asset/com.enonic.xp.app.users:1524820438/admin/common/js/_all.js:1:2222376)
    at UserStoreWizardPanel.UserItemWizardPanel.saveChanges (http://localhost:8080/admin/tool/com.enonic.xp.app.users/main/_/asset/com.enonic.xp.app.users:1524820438/js/bundle.js:1:32348)
    at UserStoreWizardPanel.saveChanges (http://localhost:8080/admin/tool/com.enonic.xp.app.users/main/_/asset/com.enonic.xp.app.users:1524820438/js/bundle.js:1:83242)
    at SaveAction.saveChanges (http://localhost:8080/admin/tool/com.enonic.xp.app.users/main/_/asset/com.enonic.xp.app.users:1524820438/admin/common/js/_all.js:1:2189134)
    at http://localhost:8080/admin/tool/com.enonic.xp.app.users/main/_/asset/com.enonic.xp.app.users:1524820438/admin/common/js/_all.js:1:2188976
    at http://localhost:8080/admin/tool/com.enonic.xp.app.users/main/_/asset/com.enonic.xp.app.users:1524820438/admin/common/js/_all.js:1:416897
    at Array.map (<anonymous>)
    at SaveAction.Action.execute (http://localhost:8080/admin/tool/com.enonic.xp.app.users/main/_/asset/com.enonic.xp.app.users:1524820438/admin/common/js/_all.js:1:416867)`

**Comment by edloidas** [comment]
Could not reproduce this bug with the latest sources.
